# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  gmail_username: Your_Username
  gmail_password: Your_Password
  secret_key_base: 'e4974c454f945e8135fdd80e1a04e38acfafd97b08e7c361b7178e58bbacbe2d7cd4aded8bc3b0ae792dfe0049cac5a09d227fd53a8da904b864a528e9b4a889'

test:
  secret_key_base: '2e0ba8bf4ded40c31a4a3363ae8c4acd52ad7dbc56e8898637b056e3e0f6022266af64c352d565c0c07c417fdbce08f65b44e006d02d8d728f80d86342f6dbd1'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: 'e4974c454f945e8135fdd80e1a04e38acfafd97b08e7c361b7178e58bbacbe2d7cd4aded8bc3b0ae792dfe0049cac5a09d227fd53a8da904b864a528e9b4a889' 
  #<%= ENV["SECRET_KEY_BASE"] %>
